services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: Ready4WorkDb
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ./
      dockerfile: Dockerfile    
    ports:
      - "5050:8080"
    environment:
      ConnectionStrings__DefaultConnection: "server=db;port=3306;database=Ready4WorkDb;user=dev;password=dev_password"
    depends_on:
      db:
        condition: service_healthy
    command: /bin/sh -c "dotnet backend.dll"
    networks:
      - db-net

networks:
  db-net:
    external: true
    name: db-net

volumes:
  db_data:
