name: Build and Push Backend

on:
  push:
    branches:
      - development
    paths:
      - 'backend/**'

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # BACKEND BUILD
      - name: Build backend Docker image
        run: |
          docker build -t backend-image:latest -f ./backend/Dockerfile ./backend
          docker save -o backend.tar backend-image:latest
          chmod 644 backend.tar
          ls -l backend.tar

      # SET UP SSH KEY FOR RSYNC
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CLOUD_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ vars.CLOUD_HOST }} >> ~/.ssh/known_hosts

      # Copy backend image to server using SCP
      - name: Copy backend image to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ vars.CLOUD_HOST }}
          username: ${{ vars.CLOUD_USER }}
          key: ${{ secrets.CLOUD_KEY }}
          source: "backend.tar"
          target: "/home/dev/ready4work/production/backend"

      # Restart backend docker container
      - name: Restart backend docker container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.CLOUD_HOST }}
          username: ${{ vars.CLOUD_USER }}
          key: ${{ secrets.CLOUD_KEY }}
          script: |
            docker load < /home/dev/ready4work/production/backend/backend.tar
            docker compose -f /home/dev/ready4work/production/docker-compose.yml up -d backend
